---
# tasks file for zabbix-server
- name: "install epel-releas and rpm packages"
  yum:
    name:
      - epel-release
      - http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      - yum-utils
    state: present

- name: "install epel-releas and rpm packages"
  shell: "percona-release setup ps80"

- name: "enable zabbix-frontend"
  template:
    src: zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo
  become: true

- name: "config manager"
  shell: yum-config-manager --enable rhel-7-server-optional-rpms

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: "install zabbix-server"
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql-scl
      - zabbix-nginx-conf-scl
      - MySQL-python
      - policycoreutils-python
      - nginx
      - percona-server-client
      - percona-server-server
    state: latest

#- name: "Create database for zabbix-server"
#  mysql: