---
# tasks file for vm1 web
- name: "install epel-release"
  yum:
    name: epel-release
    state: present
  become: true

- name: "install nginx"
  yum:
    name: nginx
    state: latest
  become: true

- name: "install zabbix package"
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: "install zabbix-agent2"
  yum:
    name: zabbix-agent2
    state: present

- name: "copy config fot zabbix agent"
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf

- name: "run zabbix agent"
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes