---
# drop rules
# NAT settings
- name: "NAT masquerade"
  iptables:
    table: 'nat'
    chain: POSTROUTING
    source: '10.10.12.0/24'
    out_interface: 'eth0'
    jump: MASQUERADE

# Rules for forwarding internal networks
- name: 'Forwarding for internal networks'
  iptables:
    table: 'filter'
    chain: FORWARD
    source: '10.10.12.0/24'
    jump: ACCEPT

# Rules for external network
- name: "Rule from external network to Router host"
  iptables:
    table: 'filter'
    chain: FORWARD
    destination: '10.10.12.0/24'
    jump: ACCEPT

# Open web ports to web server
- name: "Accept 80 port"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT

- name: "Accept 443 port"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT

# Input rules for internal networks
- name: "Internal-1 network"
  iptables:
    chain: INPUT
    source: "10.10.12.2/30"
    jump: ACCEPT

# Input rules for internal networks
- name: "Internal-1 network"
  iptables:
    chain: INPUT
    source: "10.10.12.0/24"
    jump: ACCEPT


- name: "Managment network"
  iptables:
    chain: INPUT
    source: "10.10.11.0/24"
    jump: ACCEPT

- name: "allow"
  iptables:
    chain: INPUT
    protocol: tcp
    match: conntrack
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT

# Drop policy
- name: "Drop "
  iptables:
    chain: INPUT
    protocol: tcp
    jump: DROP

- name: "Drop "
  iptables:
    chain: FORWARD
    protocol: tcp
    jump: DROP

# Systctl settings for using forwardig scheme
- name: "sysctl"
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: True

#Set time zone on hosts(we can apply this seeting in vagrantfile)
- name: "Set timezone to Asia/Irkutsk"
  timezone:
    name: Asia/Irkutsk
