---
# tasks file for web
- name: "NAT"
  ansible.builtin.iptables:
    table: 'nat'
    chain: POSTROUTING
    source: '{{ ansible-host }}'
    protocol: tcp
    jump: ACCEPT
  become: yes

- name: "Accept 80 & 443 port"
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port:
      - "80"
      - "443"
    jump: ACCEPT
  become: yes

- name: "Route to other hosts"
  ansible.builtin.iptables:
    chain: FORWARD
    source: '{{ ansible-host }}'
    dst_range: 10.10.11.0-10.10.11.254
    port: 22
    jump: ACCEPT

- name: "Drop other connection"
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP