---
all:
  hosts:
    web:
      ansible_port: 22
      ansible_host: "{{ 'outputs.external_ip_address_vm_1.value' }}"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "/home/fedor/.ssh/id_rsa"
      vars:
        input: "{{ lookup('file','.terraform.tfstate') | from_json }}"