---
#forward rules
# NAT settings fo  external connection 
- name: "NAT"
  iptables:
    table: 'nat'
    chain: POSTROUTING
    out_interface: 'eth2'
    jump: MASQUERADE

# Input rules for internal networks
- name: "Internal network"
  iptables:
    chain: INPUT
    source: "10.10.12.0/24"
    jump: ACCEPT

- name: "Managment network"
  iptables:
    chain: INPUT
    source: "10.10.11.0/24"
    jump: ACCEPT

- name: "allow"
  iptables:
    chain: INPUT
    protocol: tcp
    match: conntrack
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT

# Forwarding policy for connection to external network
- name: "Forwarding for internal networks"
  iptables:
    table: 'filter'
    chain: FORWARD
    source: "10.10.12.0/24"
    jump: ACCEPT

# Systctl settings for using forwardig scheme
- name: "sysctl"
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: True

#Set time zone on hosts(we can apply this seeting in vagrantfile)
- name: "Set timezone to Asia/Irkutsk"
  timezone:
    name: Asia/Irkutsk

